"""Data-object validation: the backend must reproduce the ground-truth CSVs
that were generated by the rule engine, and survive missing data."""

import time

import pandas as pd

from core.config import settings
from services import data_parser, user_service


def test_scores_match_ground_truth_for_all_users():
    truth = pd.read_csv(
        settings.data_dir / "processed" / "product_recommendations.csv"
    ).set_index("user_id")
    users = data_parser.load_merged_users()
    assert len(users) == len(truth) == 500
    for u in users:
        r = user_service.score(u, with_details=False)
        assert r["credit_score"] == truth.loc[u["user_id"], "final_credit_score"], u[
            "user_id"
        ]
        assert r["risk_tier"] == truth.loc[u["user_id"], "risk_tier"]


def test_factor_points_match_factor_analysis_csv():
    fa = pd.read_csv(settings.data_dir / "processed" / "factor_analysis.csv")
    row = fa[fa.user_id == "USR_002"]
    r = user_service.score(
        next(u for u in data_parser.load_merged_users() if u["user_id"] == "USR_002")
    )
    got = {f["factor"]: f["score"] for f in r["explanation"]["all_factors"]}
    assert got == dict(zip(row.factor, row.score))


def test_pd_is_inverse_of_score():
    assert user_service.probability_of_default(1000) == 0
    assert user_service.probability_of_default(750) == 0.25
    assert 0 <= user_service.probability_of_default(-50) <= 1


def test_missing_data_does_not_crash():
    """Robustness: no utility / payment history, no spend data, junk values."""
    r = user_service.score({"user_id": "X", "monthly_income": 3000})
    assert 0 <= r["credit_score"] <= 1000
    assert (
        "on_time_rate" in r["missing_fields"]
        and "digital_payment_rate" in r["missing_fields"]
    )
    assert r["data_completeness"] < 1
    # entirely empty and dirty inputs
    assert user_service.score({})["credit_score"] >= 0
    dirty = user_service.score(
        {"monthly_income": "abc", "on_time_rate": 7, "dti": -2, "housing": None}
    )
    assert 0 <= dirty["credit_score"] <= 1000


def test_missing_fields_never_beat_full_data():
    full = next(u for u in data_parser.load_merged_users() if u["user_id"] == "USR_002")
    partial = {
        k: v
        for k, v in full.items()
        if k not in ("on_time_rate", "digital_payment_rate")
    }
    assert (
        user_service.score(partial)["credit_score"]
        <= user_service.score(full)["credit_score"]
    )


def test_latency_well_under_budget():
    users = data_parser.load_merged_users()
    start = time.perf_counter()
    for u in users:
        user_service.score(u)
    assert (
        time.perf_counter() - start < 15
    )  # brief allows 15-30s end to end for a user; this is all 500


def test_transaction_feature_derivation():
    csv = (
        b"date,amount,category,type,status\n2024-01-01,5000,Salary,CREDIT,Completed\n"
        b"2024-01-05,900,Rent,DEBIT,Completed\n2024-01-09,100,Utility Bill,DEBIT,Late\n"
        b"2024-02-01,5000,Salary,CREDIT,Completed\n2024-02-05,900,Rent,DEBIT,Completed\n"
        b"2024-02-20,500,Savings,DEBIT,Completed\n2024-02-21,300,Food,DEBIT,Completed\n"
    )
    f = data_parser.features_from_transactions(data_parser.parse_transactions(csv))
    assert f["housing"] == "rent" and f["rent_on_time_months"] == 2
    assert f["delinq_30plus"] == 1 and 0 < f["on_time_rate"] < 1
    assert f["monthly_income"] == 5000
